import "./globals.css";
import Navbar from "@/components/general/Navbar";
import { GoogleOAuthProvider } from '@react-oauth/google';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GoogleOAuthProvider clientId="api google">
            <Navbar />
            {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
