import "./globals.css";
import Navbar from "@/components/general/Navbar";
import { GoogleOAuthProvider } from '@react-oauth/google';
import { TagFilterProvider } from "@/hooks/tagsContext";
import { LoggedInProvider } from "@/hooks/loggedInContext";
import { Toaster } from 'sonner'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID}>
          <LoggedInProvider>
            <TagFilterProvider>
              <Navbar />
              <Toaster richColors position="top-right" />
              {children}
            </TagFilterProvider>
          </LoggedInProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
