services:
  database:
    #    image: postgres:15
    image: mateogonzalezz/stoa-database:latest
    container_name: stoa-database
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  frontend:
    container_name: stoa-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    container_name: stoa-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

name: stoa-inso2
