name: Backend push CI

on:
  push:
    branches: ["main", "dev", "fix/sonar-issues"]

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Build with Gradle (no tests)
        run: cd backend && ./gradlew build -x test

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Run tests
        run: cd backend && ./gradlew test
        
  sonar-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('backend/**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Give permissions to gradlew
        run: chmod +x backend/gradlew
      - name: Build and analyze with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: cd backend && ./gradlew build sonar --info
